import { StyleSheet } from "react-native";

import { ThemePalette } from "./theme";

export function createStyles(colors: ThemePalette) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    appShell: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 136,
      gap: 12,
    },
    backgroundOrnamentTop: {
      position: "absolute",
      top: -50,
      right: -10,
      width: 220,
      height: 220,
      borderRadius: 110,
      backgroundColor: colors.ornamentTop,
      opacity: 0.22,
    },
    backgroundOrnamentBottom: {
      position: "absolute",
      bottom: 120,
      left: -70,
      width: 260,
      height: 260,
      borderRadius: 130,
      backgroundColor: colors.ornamentBottom,
      opacity: 0.14,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 16,
    },
    headerTextWrap: {
      flex: 1,
    },
    eyebrowRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 6,
    },
    eyebrow: {
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1.2,
      color: colors.accent,
    },
    eyebrowDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.accent,
    },
    title: {
      fontSize: 20,
      lineHeight: 24,
      fontWeight: "900",
      color: colors.ink,
      marginBottom: 4,
    },
    subtitle: {
      color: colors.muted,
      fontSize: 12,
      lineHeight: 16,
      maxWidth: 250,
    },
    headerSpacer: {
      width: 56,
      height: 56,
    },
    settingsButton: {
      width: 56,
      height: 56,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
      alignItems: "center",
      justifyContent: "center",
    },
    authShell: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 24,
      justifyContent: "center",
      gap: 18,
    },
    authHero: {
      borderRadius: 28,
      padding: 22,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 8,
    },
    authHeroEyebrow: {
      color: colors.accentSoft,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    authHeroTitle: {
      color: colors.heroText,
      fontSize: 24,
      lineHeight: 30,
      fontWeight: "900",
    },
    authHeroCopy: {
      color: colors.heroMuted,
      fontSize: 13,
      lineHeight: 19,
    },
    authCard: {
      backgroundColor: colors.card,
      borderRadius: 28,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 14,
    },
    authModeRow: {
      flexDirection: "row",
      gap: 10,
    },
    authModeButton: {
      flex: 1,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
      paddingVertical: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    authModeButtonActive: {
      backgroundColor: colors.accent,
      borderColor: colors.accentStrong,
    },
    authModeText: {
      color: colors.ink,
      fontSize: 14,
      fontWeight: "800",
    },
    authModeTextActive: {
      color: "#03162d",
    },
    authFieldWrap: {
      gap: 6,
    },
    authLabel: {
      color: colors.ink,
      fontSize: 13,
      fontWeight: "800",
    },
    authInput: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 14,
      color: colors.ink,
      fontSize: 14,
    },
    authError: {
      color: colors.danger,
      fontSize: 12,
      lineHeight: 17,
    },
    leagueSuccess: {
      color: colors.success,
      fontSize: 12,
      lineHeight: 17,
    },
    authSubmitButton: {
      backgroundColor: colors.accentStrong,
      borderRadius: 18,
      paddingVertical: 15,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 4,
    },
    authSubmitText: {
      color: colors.heroText,
      fontSize: 14,
      fontWeight: "900",
    },
    loadingCard: {
      backgroundColor: colors.cardStrong,
      borderRadius: 24,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 8,
    },
    loadingTitle: {
      color: colors.ink,
      fontSize: 16,
      fontWeight: "900",
    },
    loadingCopy: {
      color: colors.muted,
      fontSize: 13,
      lineHeight: 18,
    },
    section: {
      gap: 8,
    },
    sectionTitle: {
      color: colors.ink,
      fontSize: 15,
      fontWeight: "900",
    },
    sectionCopy: {
      color: colors.muted,
      fontSize: 12,
      lineHeight: 16,
    },
    worldCupHero: {
      borderRadius: 30,
      padding: 18,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.line,
      backgroundColor: colors.hero,
    },
    heroTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 14,
    },
    heroChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: "rgba(255,255,255,0.10)",
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    heroChipText: {
      color: colors.heroText,
      fontWeight: "800",
      fontSize: 12,
      textTransform: "uppercase",
      letterSpacing: 0.7,
    },
    heroMeta: {
      color: colors.heroMuted,
      fontSize: 12,
      fontWeight: "700",
    },
    heroTitle: {
      color: colors.heroText,
      fontSize: 20,
      lineHeight: 24,
      fontWeight: "900",
      marginBottom: 4,
    },
    heroDescription: {
      color: colors.heroMuted,
      fontSize: 12,
      lineHeight: 17,
      marginBottom: 0,
      maxWidth: 280,
    },
    sectionRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    sectionBadge: {
      backgroundColor: colors.chipBg,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.line,
    },
    sectionBadgeText: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    card: {
      backgroundColor: colors.card,
      borderRadius: 26,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 8,
    },
    cardEyebrow: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    cardTitle: {
      color: colors.ink,
      fontSize: 17,
      lineHeight: 22,
      fontWeight: "900",
    },
    cardDescription: {
      color: colors.muted,
      fontSize: 13,
      lineHeight: 18,
    },
    homeMatchCard: {
      backgroundColor: colors.cardStrong,
      borderRadius: 24,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 10,
    },
    homeMatchTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 10,
    },
    homeMatchClock: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: "700",
      flex: 1,
      textAlign: "right",
    },
    homeMatchTeamsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    homeTeamInline: {
      flex: 1,
      alignItems: "center",
      gap: 8,
    },
    homeTeamInlineName: {
      color: colors.ink,
      fontSize: 13,
      fontWeight: "900",
      textAlign: "center",
    },
    homeVsBadge: {
      minWidth: 62,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.line,
      paddingHorizontal: 8,
    },
    homeVsText: {
      color: colors.accent,
      fontSize: 13,
      fontWeight: "900",
    },
    homeMatchMeta: {
      color: colors.muted,
      fontSize: 12,
      lineHeight: 18,
    },
    predictButton: {
      backgroundColor: colors.accent,
      borderRadius: 16,
      paddingVertical: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    predictButtonDisabled: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
    },
    predictButtonText: {
      color: "#03162d",
      fontSize: 13,
      fontWeight: "900",
    },
    predictButtonTextDisabled: {
      color: colors.muted,
    },
    predictButtonDone: {
      backgroundColor: colors.accentSoft,
      borderWidth: 1,
      borderColor: colors.line,
    },
    predictButtonTextDone: {
      color: colors.accent,
    },
    featuredMatchCard: {
      backgroundColor: colors.cardStrong,
      borderRadius: 28,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 16,
    },
    matchHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 12,
    },
    matchMetaWrap: {
      flex: 1,
      gap: 8,
    },
    matchMetaChip: {
      alignSelf: "flex-start",
      backgroundColor: colors.accentSoft,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    matchMetaChipText: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    matchKickoff: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: "700",
    },
    matchTeamsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 14,
    },
    teamBlock: {
      flex: 1,
      alignItems: "center",
      gap: 8,
    },
    teamFlagImage: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.surface,
    },
    teamFlag: {
      fontSize: 28,
    },
    teamName: {
      color: colors.ink,
      fontSize: 16,
      fontWeight: "900",
      textAlign: "center",
    },
    versusBadge: {
      width: 56,
      height: 48,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.line,
      paddingHorizontal: 6,
    },
    versusText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "900",
      letterSpacing: 0.6,
    },
    matchVenue: {
      color: colors.muted,
      fontSize: 13,
      textAlign: "center",
      marginTop: -4,
    },
    matchInfoRow: {
      flexDirection: "row",
      gap: 10,
      flexWrap: "wrap",
    },
    infoPill: {
      backgroundColor: colors.surface,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.line,
    },
    infoPillText: {
      color: colors.ink,
      fontSize: 12,
      fontWeight: "700",
    },
    questionCard: {
      backgroundColor: colors.surface,
      borderRadius: 22,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 12,
    },
    questionPrompt: {
      color: colors.ink,
      fontSize: 15,
      fontWeight: "800",
      lineHeight: 20,
    },
    optionsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    filterRow: {
      flexDirection: "row",
      gap: 8,
      paddingRight: 12,
    },
    filterWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    optionPill: {
      minWidth: 58,
      backgroundColor: colors.chipBg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.line,
      paddingHorizontal: 14,
      paddingVertical: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    optionPillActive: {
      backgroundColor: colors.accent,
      borderColor: colors.accentStrong,
    },
    optionPillText: {
      color: colors.ink,
      fontSize: 13,
      fontWeight: "800",
    },
    optionPillTextActive: {
      color: "#03162d",
    },
    questionInsightRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    questionInsight: {
      color: colors.muted,
      fontSize: 12,
      lineHeight: 18,
      flex: 1,
    },
    fixtureCard: {
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 10,
    },
    fixtureTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    fixtureDay: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    fixtureTime: {
      color: colors.ink,
      fontSize: 15,
      fontWeight: "900",
    },
    fixtureStatus: {
      color: colors.heroText,
      fontSize: 11,
      fontWeight: "800",
      backgroundColor: colors.accentStrong,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      overflow: "hidden",
    },
    fixtureTeamsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    fixtureTeamName: {
      color: colors.ink,
      fontSize: 13,
      fontWeight: "800",
      flex: 1,
    },
    fixtureFlag: {
      fontSize: 22,
    },
    fixtureFlagImage: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.surface,
    },
    fixtureBottomRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 10,
    },
    fixtureMeta: {
      color: colors.muted,
      fontSize: 12,
      flex: 1,
    },
    fixtureQuestions: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "800",
    },
    miniStatsRow: {
      flexDirection: "row",
      gap: 12,
    },
    miniStatCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 6,
    },
    miniStatValue: {
      color: colors.ink,
      fontSize: 24,
      fontWeight: "900",
    },
    miniStatLabel: {
      color: colors.muted,
      fontSize: 12,
      lineHeight: 18,
    },
    groupCard: {
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 14,
    },
    groupTitleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 10,
    },
    groupTitleWrap: {
      flex: 1,
      gap: 4,
    },
    groupTitle: {
      color: colors.ink,
      fontSize: 15,
      fontWeight: "900",
    },
    groupSubtitle: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: "700",
    },
    tableHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.line,
      gap: 8,
    },
    tableHeaderTeam: {
      flex: 1,
      color: colors.muted,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    tableHeaderCell: {
      width: 34,
      textAlign: "center",
      color: colors.muted,
      fontSize: 11,
      fontWeight: "800",
    },
    groupRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.line,
      gap: 8,
    },
    groupRank: {
      width: 18,
      color: colors.accent,
      fontSize: 12,
      fontWeight: "900",
    },
    groupTeamWrap: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    groupTeamFlag: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.surface,
    },
    groupTeamName: {
      flex: 1,
      color: colors.ink,
      fontSize: 12,
      fontWeight: "700",
    },
    groupCell: {
      width: 34,
      textAlign: "center",
      color: colors.ink,
      fontSize: 12,
      fontWeight: "800",
    },
    profileHero: {
      backgroundColor: colors.cardStrong,
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 28,
      padding: 18,
      alignItems: "center",
      gap: 8,
    },
    avatar: {
      width: 78,
      height: 78,
      borderRadius: 39,
      backgroundColor: colors.accentSoft,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 6,
      borderWidth: 1,
      borderColor: colors.line,
    },
    avatarText: {
      color: colors.ink,
      fontSize: 30,
      fontWeight: "900",
    },
    profileName: {
      color: colors.ink,
      fontSize: 18,
      fontWeight: "900",
    },
    profileHandle: {
      color: colors.muted,
      fontSize: 13,
    },
    profileContent: {
      gap: 14,
    },
    activeLeagueChip: {
      marginTop: 8,
      backgroundColor: colors.chipBg,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.line,
      paddingHorizontal: 12,
      paddingVertical: 7,
    },
    activeLeagueChipText: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    settingsPanel: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.line,
      padding: 18,
      gap: 10,
    },
    settingsTitle: {
      color: colors.ink,
      fontSize: 15,
      fontWeight: "900",
    },
    settingsCopy: {
      color: colors.muted,
      fontSize: 12,
      lineHeight: 16,
    },
    settingsPrimaryAction: {
      marginTop: 4,
      borderRadius: 18,
      backgroundColor: colors.accentStrong,
      paddingVertical: 15,
      paddingHorizontal: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    settingsPrimaryActionText: {
      color: colors.heroText,
      fontSize: 14,
      fontWeight: "900",
    },
    adminStatusRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 2,
    },
    adminStatusChip: {
      backgroundColor: colors.chipBg,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.line,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    adminStatusChipText: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: "800",
    },
    adminScenarioActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    adminScenarioButton: {
      minWidth: 54,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 14,
      backgroundColor: colors.accentStrong,
      alignItems: "center",
      justifyContent: "center",
    },
    adminScenarioButtonText: {
      color: colors.heroText,
      fontSize: 12,
      fontWeight: "900",
    },
    userLeagueCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: colors.surface,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.line,
      padding: 14,
    },
    userLeagueBody: {
      flex: 1,
      gap: 4,
    },
    userLeagueName: {
      color: colors.ink,
      fontSize: 14,
      fontWeight: "900",
    },
    userLeagueMeta: {
      color: colors.muted,
      fontSize: 12,
      lineHeight: 17,
    },
    userLeagueAction: {
      minWidth: 88,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 14,
      backgroundColor: colors.accentStrong,
      alignItems: "center",
      justifyContent: "center",
    },
    userLeagueActionText: {
      color: colors.heroText,
      fontSize: 12,
      fontWeight: "900",
    },
    userLeagueActiveBadge: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 14,
      backgroundColor: colors.accentSoft,
      borderWidth: 1,
      borderColor: colors.line,
    },
    userLeagueActiveText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "900",
    },
    predictionSettledBadge: {
      backgroundColor: colors.accentStrong,
      borderColor: colors.accentStrong,
    },
    predictionSettledBadgeText: {
      color: colors.heroText,
    },
    historyListRight: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    themeSwitchRow: {
      flexDirection: "row",
      gap: 10,
      marginTop: 8,
    },
    themeOption: {
      flex: 1,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
      paddingVertical: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    themeOptionActive: {
      backgroundColor: colors.accent,
      borderColor: colors.accentStrong,
    },
    themeOptionText: {
      color: colors.ink,
      fontSize: 14,
      fontWeight: "800",
    },
    themeOptionTextActive: {
      color: "#03162d",
    },
    profileStatsRow: {
      flexDirection: "row",
      gap: 10,
    },
    profileStatCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 18,
      padding: 14,
      gap: 6,
    },
    profileStatValue: {
      color: colors.ink,
      fontSize: 17,
      fontWeight: "900",
    },
    profileStatLabel: {
      color: colors.muted,
      fontSize: 12,
    },
    logoutWrap: {
      paddingHorizontal: 4,
      paddingBottom: 8,
    },
    logoutButton: {
      borderRadius: 18,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.line,
      paddingVertical: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    logoutButtonText: {
      color: colors.ink,
      fontSize: 14,
      fontWeight: "900",
    },
    leaderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: colors.surface,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.line,
      padding: 14,
    },
    leaderNumber: {
      width: 28,
      color: colors.accent,
      fontSize: 18,
      fontWeight: "900",
      textAlign: "center",
    },
    leaderBody: {
      flex: 1,
      gap: 2,
    },
    leaderName: {
      color: colors.ink,
      fontSize: 14,
      fontWeight: "900",
    },
    calendarHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 10,
    },
    calendarMonthRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    calendarArrow: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
      alignItems: "center",
      justifyContent: "center",
    },
    calendarMonthLabel: {
      color: colors.ink,
      fontSize: 13,
      fontWeight: "800",
      textTransform: "capitalize",
      minWidth: 100,
      textAlign: "center",
    },
    calendarWeekHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    calendarWeekLabel: {
      width: "13%",
      color: colors.muted,
      fontSize: 11,
      fontWeight: "800",
      textAlign: "center",
    },
    calendarGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      rowGap: 6,
    },
    calendarDay: {
      width: "13%",
      aspectRatio: 1,
      borderRadius: 14,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
    },
    calendarDayMuted: {
      opacity: 0.35,
    },
    calendarDayHasMatch: {
      borderColor: colors.accent,
    },
    calendarDayActive: {
      backgroundColor: colors.accent,
      borderColor: colors.accentStrong,
    },
    calendarDayText: {
      color: colors.ink,
      fontSize: 13,
      fontWeight: "800",
    },
    calendarDayTextMuted: {
      color: colors.muted,
    },
    calendarDayTextActive: {
      color: "#03162d",
    },
    calendarDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.accent,
    },
    leaderMeta: {
      color: colors.muted,
      fontSize: 12,
      lineHeight: 18,
    },
    leaderPointsWrap: {
      alignItems: "flex-end",
      gap: 4,
    },
    leaderPoints: {
      color: colors.ink,
      fontSize: 20,
      fontWeight: "900",
    },
    leaderBadge: {
      color: colors.heroText,
      fontSize: 11,
      fontWeight: "800",
      backgroundColor: colors.accentStrong,
      overflow: "hidden",
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 999,
    },
    leaderBadgePlaceholder: {
      backgroundColor: colors.line,
      color: colors.muted,
    },
    copyIconButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.accent,
    },
    leagueActionsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    inviteCodeChip: {
      alignSelf: "auto",
      gap: 2,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 8,
      flexShrink: 1,
    },
    inviteCodeLabel: {
      color: colors.muted,
      fontSize: 10,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    inviteCodeValue: {
      color: colors.ink,
      fontSize: 14,
      fontWeight: "900",
      letterSpacing: 0.8,
    },
    copyToast: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: colors.accentSoft,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.line,
      paddingHorizontal: 12,
      paddingVertical: 10,
      alignSelf: "flex-start",
    },
    copyToastText: {
      color: colors.success,
      fontSize: 12,
      fontWeight: "800",
    },
    leaveLeagueButton: {
      backgroundColor: colors.danger,
      borderRadius: 14,
      paddingVertical: 10,
      paddingHorizontal: 12,
      alignItems: "center",
      justifyContent: "center",
      minWidth: 108,
    },
    leaveLeagueButtonText: {
      color: colors.heroText,
      fontSize: 12,
      fontWeight: "900",
    },
    appModalBackdrop: {
      flex: 1,
      backgroundColor: colors.overlay,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 20,
    },
    appModalOverlay: {
      ...StyleSheet.absoluteFill,
    },
    appModalCard: {
      width: "100%",
      maxWidth: 380,
      backgroundColor: colors.cardStrong,
      borderRadius: 28,
      borderWidth: 1,
      borderColor: colors.line,
      padding: 22,
      gap: 12,
    },
    appModalIconWrap: {
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
    },
    appModalTitle: {
      color: colors.ink,
      fontSize: 20,
      fontWeight: "900",
    },
    appModalBody: {
      color: colors.muted,
      fontSize: 13,
      lineHeight: 19,
    },
    appModalActions: {
      flexDirection: "row",
      gap: 10,
      marginTop: 6,
    },
    appModalSecondaryButton: {
      flex: 1,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
      paddingVertical: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    appModalSecondaryButtonText: {
      color: colors.ink,
      fontSize: 13,
      fontWeight: "800",
    },
    appModalPrimaryButton: {
      flex: 1,
      borderRadius: 16,
      backgroundColor: colors.accentStrong,
      paddingVertical: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    appModalDangerButton: {
      backgroundColor: colors.danger,
    },
    appModalPrimaryButtonText: {
      color: colors.heroText,
      fontSize: 13,
      fontWeight: "900",
    },
    podiumWrap: {
      flexDirection: "row",
      alignItems: "flex-end",
      justifyContent: "center",
      gap: 10,
      marginTop: 2,
    },
    podiumColumn: {
      flex: 1,
      maxWidth: 110,
      justifyContent: "flex-end",
    },
    podiumColumnGold: {
      minHeight: 182,
    },
    podiumColumnSilver: {
      minHeight: 156,
    },
    podiumColumnBronze: {
      minHeight: 140,
    },
    podiumCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.line,
      paddingHorizontal: 12,
      paddingVertical: 14,
      alignItems: "center",
      gap: 4,
    },
    podiumCardGold: {
      backgroundColor: "rgba(255, 204, 64, 0.18)",
      borderColor: "#ffc53d",
      minHeight: 164,
    },
    podiumCardSilver: {
      backgroundColor: "rgba(194, 204, 219, 0.18)",
      borderColor: "#c9d2de",
      minHeight: 142,
    },
    podiumCardBronze: {
      backgroundColor: "rgba(205, 127, 50, 0.16)",
      borderColor: "#cd7f32",
      minHeight: 126,
    },
    podiumCardPlaceholder: {
      backgroundColor: colors.surface,
      borderColor: colors.line,
      opacity: 0.72,
    },
    podiumRankBadge: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.accentStrong,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 2,
    },
    podiumRankBadgeGold: {
      backgroundColor: "#f6b600",
    },
    podiumRankBadgeSilver: {
      backgroundColor: "#a8b4c7",
    },
    podiumRankBadgeBronze: {
      backgroundColor: "#c37a35",
    },
    podiumRankText: {
      color: colors.heroText,
      fontSize: 14,
      fontWeight: "900",
    },
    podiumName: {
      color: colors.ink,
      fontSize: 13,
      fontWeight: "900",
      textAlign: "center",
    },
    podiumPoints: {
      color: colors.ink,
      fontSize: 24,
      fontWeight: "900",
    },
    podiumMeta: {
      color: colors.muted,
      fontSize: 11,
      lineHeight: 15,
      textAlign: "center",
    },
    podiumSkeletonName: {
      width: "78%",
      height: 12,
      borderRadius: 999,
      backgroundColor: colors.line,
      marginTop: 4,
    },
    podiumSkeletonScore: {
      width: 40,
      height: 22,
      borderRadius: 999,
      backgroundColor: colors.line,
      marginTop: 4,
    },
    podiumSkeletonMeta: {
      width: "68%",
      height: 10,
      borderRadius: 999,
      backgroundColor: colors.line,
      marginTop: 4,
    },
    placeholderText: {
      color: colors.muted,
    },
    leaderRowPlaceholder: {
      opacity: 0.78,
    },
    leaderSkeletonName: {
      width: "64%",
      height: 12,
      borderRadius: 999,
      backgroundColor: colors.line,
    },
    leaderSkeletonMeta: {
      width: "84%",
      height: 10,
      borderRadius: 999,
      backgroundColor: colors.line,
      marginTop: 6,
    },
    leaderSkeletonScore: {
      width: 28,
      height: 18,
      borderRadius: 999,
      backgroundColor: colors.line,
    },
    leaderSkeletonBadge: {
      width: 46,
      height: 18,
      borderRadius: 999,
      backgroundColor: colors.line,
    },
    settingsDangerAction: {
      marginTop: 4,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: colors.danger,
      borderRadius: 16,
      paddingVertical: 14,
    },
    settingsDangerActionText: {
      color: colors.heroText,
      fontSize: 13,
      fontWeight: "900",
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 14,
    },
    predictionModal: {
      width: "100%",
      maxHeight: "88%",
      backgroundColor: colors.bg,
      borderRadius: 30,
      paddingTop: 16,
      paddingHorizontal: 16,
      paddingBottom: 24,
      borderWidth: 1,
      borderColor: colors.line,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 12,
      marginBottom: 14,
    },
    modalHeaderTextWrap: {
      flex: 1,
      gap: 4,
    },
    modalEyebrow: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    modalTitle: {
      color: colors.ink,
      fontSize: 16,
      fontWeight: "900",
      lineHeight: 22,
    },
    modalCloseButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.line,
      alignItems: "center",
      justifyContent: "center",
    },
    modalScrollContent: {
      gap: 12,
      paddingBottom: 24,
    },
    modalMatchCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 6,
    },
    modalMatchTitle: {
      color: colors.ink,
      fontSize: 18,
      fontWeight: "900",
      textAlign: "center",
    },
    modalMatchMeta: {
      color: colors.muted,
      fontSize: 12,
      textAlign: "center",
    },
    historyScoreBadge: {
      alignSelf: "center",
      marginTop: 4,
      backgroundColor: colors.accentSoft,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: colors.line,
    },
    historyScoreBadgeText: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "900",
    },
    modalLoadingRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: colors.surface,
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: colors.line,
    },
    modalQuestionCard: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.line,
      gap: 10,
    },
    modalQuestionPrompt: {
      color: colors.ink,
      fontSize: 14,
      fontWeight: "800",
      lineHeight: 18,
      flex: 1,
      marginRight: 8,
    },
    modalPointsBadge: {
      backgroundColor: colors.accentSoft,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
      flexShrink: 0,
    },
    modalPointsBadgeText: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "900",
    },
    modalOptionsWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: 8,
    },
    modalOptionButton: {
      minWidth: 72,
      backgroundColor: colors.chipBg,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.line,
      paddingHorizontal: 12,
      paddingVertical: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    modalOptionButtonActive: {
      backgroundColor: colors.accent,
      borderColor: colors.accentStrong,
    },
    modalOptionText: {
      color: colors.ink,
      fontSize: 13,
      fontWeight: "800",
    },
    modalOptionTextActive: {
      color: "#03162d",
    },
    historyOptionCorrect: {
      backgroundColor: colors.success,
      borderColor: colors.success,
    },
    historyOptionWrong: {
      backgroundColor: colors.danger,
      borderColor: colors.danger,
    },
    historyOptionResultText: {
      color: colors.heroText,
    },
    modalInsightRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    modalInsightText: {
      flex: 1,
      color: colors.muted,
      fontSize: 12,
      lineHeight: 17,
    },
    modalSubmitButton: {
      backgroundColor: colors.accentStrong,
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 6,
    },
    modalSubmitButtonText: {
      color: colors.heroText,
      fontSize: 14,
      fontWeight: "900",
    },
    splashContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 16,
    },
    splashIconWrap: {
      width: 110,
      height: 110,
      borderRadius: 55,
      backgroundColor: "rgba(255,255,255,0.14)",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.22)",
    },
    splashTitle: {
      color: colors.heroText,
      fontSize: 30,
      fontWeight: "900",
      textAlign: "center",
      letterSpacing: 0.4,
    },
    splashSubtitle: {
      color: colors.heroMuted,
      fontSize: 14,
      textAlign: "center",
      lineHeight: 20,
    },
    bottomNavShell: {
      position: "absolute",
      left: 16,
      right: 16,
      bottom: 14,
      shadowColor: "#000",
      shadowOpacity: 0.28,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 12 },
    },
    bottomNav: {
      flexDirection: "row",
      borderRadius: 30,
      padding: 6,
      borderWidth: 1,
      borderColor: colors.line,
      overflow: "hidden",
      position: "relative",
    },
    bottomNavGlow: {
      position: "absolute",
      width: 180,
      height: 180,
      borderRadius: 90,
      backgroundColor: colors.navGlow,
      top: -64,
      right: -20,
    },
    navItem: {
      flex: 1,
      borderRadius: 22,
      paddingVertical: 2,
      alignItems: "center",
      justifyContent: "center",
      minHeight: 64,
    },
    navItemActive: {
      width: "100%",
      borderRadius: 22,
      paddingVertical: 10,
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      shadowColor: colors.accent,
      shadowOpacity: 0.24,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
    },
    navIconWrap: {
      marginBottom: 4,
    },
    navLabel: {
      color: colors.navIdleText,
      fontSize: 11,
      fontWeight: "800",
      textAlign: "center",
    },
    navLabelActive: {
      color: colors.navActiveText,
    },
  });
}

export type AppStyles = ReturnType<typeof createStyles>;
